return {
  {
    "cuencapablo/rosebones",
    config = function()
      require("rosebones").setup({
        transparency = true,
      })
      vim.cmd.colorscheme("rosebones")
    end,
  },
  {
    "xiyaowong/transparent.nvim",
    lazy = false,
    priority = 999,
    opts = {
      extra_groups = {
        "NormalFloat",
        "FloatBorder",
        "NeoTreeNormal",
        "NeoTreeNormalNC",
        "NeoTreeWinSeparator",
        "NeoTreeEndOfBuffer",
        "StatusLineNC",
        "StatusLine",
        "NvimTreeStatusLine",
        "WhichKeyFloat",
        "WhichKeyBorder",
        "Folded",
        "SpecialKey",
        "VertSplit",
        "TelescopeBorder",
        "TelescopeNormal",
        "TelescopePromptNormal",
        "TelescopeResultsNormal",
        "TelescopeSelection",
        "TelescopeSelectionCaret",
      },
      groups = {
        "Normal",
        "NormalNC",
        "Comment",
        "Constant",
        "Special",
        "Identifier",
        "Statement",
        "PreProc",
        "Type",
        "Underlined",
        "Todo",
        "String",
        "Function",
        "Conditional",
        "Repeat",
        "Operator",
        "Structure",
        "LineNr",
        "NonText",
        "SignColumn",
        "StatusLine",
        "StatusLineNC",
        "EndOfBuffer",
      },
    },
  },
}
